import { Noto_Serif } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

const noto = Noto_Serif({ subsets: ["latin"] });

export const metadata = {
  title: "CNodeJS 社区",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-Hans">
      <body
        className={
          noto.className +
          " min-h-screen flex flex-col justify-between bg-gray-50"
        }
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
