import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CNodeJS 社区",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-Hans">
      <body className={inter.className + " h-full bg-gray-50"}>
        <Header />
        {children}
      </body>
    </html>
  );
}
